import { defineConfig } from 'vitest/config';

export default defineConfig({
  test: {
    environment: 'jsdom',
    globals: true,
    include: ['packages/**/*.test.ts', 'packages/**/*.test.tsx'],
    coverage: {
      provider: 'v8',
      reporter: ['text', 'lcov'],
      include: [
        'packages/headless/src/index.ts',
        'packages/headless/src/hooks/index.ts',
        'packages/headless/src/hooks/useDisclosure/index.ts',
        'packages/headless/src/hooks/useDisclosure/useDisclosure.ts',
        'packages/headless/src/hooks/useModal/index.ts',
        'packages/headless/src/hooks/useModal/useModal.ts',
        'packages/headless/src/hooks/useAccordion/index.ts',
        'packages/headless/src/hooks/useAccordion/useAccordion.ts',
        'packages/headless/src/hooks/useTabs/index.ts',
        'packages/headless/src/hooks/useTabs/useTabs.ts',
        'packages/headless/src/hooks/usePagination/index.ts',
        'packages/headless/src/hooks/usePagination/usePagination.ts',
        'packages/headless/src/hooks/useControllableState/index.ts',
        'packages/headless/src/hooks/useControllableState/useControllableState.ts',
        'packages/headless/src/hooks/useMenu/index.ts',
        'packages/headless/src/hooks/useMenu/useMenu.ts',
        'packages/headless/src/hooks/useSelect/index.ts',
        'packages/headless/src/hooks/useSelect/useSelect.ts',
        'packages/headless/src/hooks/useCombobox/index.ts',
        'packages/headless/src/hooks/useCombobox/useCombobox.ts',
        'packages/headless/src/hooks/useTypeahead/index.ts',
        'packages/headless/src/hooks/useTypeahead/useTypeahead.ts',
        'packages/headless/src/hooks/useListbox/index.ts',
        'packages/headless/src/hooks/useListbox/useListbox.ts',
        'packages/headless/src/hooks/useToggle/index.ts',
        'packages/headless/src/hooks/useToggle/useToggle.ts',
        'packages/primitives/src/index.ts',
        'packages/primitives/src/controls/index.ts',
        'packages/primitives/src/controls/Button/index.ts',
        'packages/primitives/src/controls/Button/Button.tsx',
        'packages/primitives/src/display/index.ts',
        'packages/primitives/src/display/Card/index.ts',
        'packages/primitives/src/display/Card/Card.tsx',
        'packages/primitives/src/layout/index.ts',
        'packages/primitives/src/layout/Box/index.ts',
        'packages/primitives/src/layout/Box/Box.tsx',
        'packages/grid-core/src/index.ts',
        'packages/grid-core/src/useGrid/index.ts',
        'packages/grid-core/src/useGrid/useGrid.tsx',
        'packages/tailwind-wrappers/src/index.ts',
        'packages/tailwind-wrappers/src/TwButton/index.ts',
        'packages/tailwind-wrappers/src/TwButton/TwButton.tsx',
        'packages/tailwind-wrappers/src/TwTable/index.ts',
        'packages/tailwind-wrappers/src/TwTable/TwTable.tsx',
      ],
      thresholds: {
        branches: 80,
        functions: 80,
        lines: 80,
        statements: 80,
      },
    },
  },
});